# Site Settings
title: Veeksha Lobo
description: Data Scientist | ML Engineer
url: https://veeksha24.github.io
baseurl: "/Veeksha24.github.io-portfolio"

# Author Info
author:
  name: Veeksha Lobo
  email: you@email.com
  github: Veeksha24
  linkedin: yourusername

# Theme
remote_theme: alshedivat/al-folio

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

# Build
markdown: kramdown
highlighter: rouge
